<a href="https://colab.research.google.com/github/ShobigaBoopeshKumar/Python_Libraries/blob/main/PANDAS%5CPython_Projects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Student Mark Analyzer**

In [ ]:
import numpy as np
stu=int(input("Enter the no of Students\t:"))
sub=int(input("Enter the no of Subjects\t:"))
marks=np.zeros((stu,sub))
for i in range(stu):
  for j in range(sub):
    marks[i][j]=int(input(f"Enter the marks of student {i+1} in subject {j+1} :"))
print(marks)


Enter the no of Students	:3
Enter the no of Subjects	:3
Enter the marks of student 1 in subject 1 :95
Enter the marks of student 1 in subject 2 :93
Enter the marks of student 1 in subject 3 :91
Enter the marks of student 2 in subject 1 :85
Enter the marks of student 2 in subject 2 :83
Enter the marks of student 2 in subject 3 :81
Enter the marks of student 3 in subject 1 :75
Enter the marks of student 3 in subject 2 :73
Enter the marks of student 3 in subject 3 :71
[[95. 93. 91.]
 [85. 83. 81.]
 [75. 73. 71.]]


In [ ]:
# The avg marks of the each student
avg_marks_stu=np.mean(marks,axis=1)
print(avg_marks_stu)

# The avg mark of each subject

avg_marks_sub=np.mean(marks,axis=0)
print(avg_marks_sub)


[93. 83. 73.]
[85. 83. 81.]


In [ ]:
# The total mark of each student
total_mark_stu=np.sum(marks,axis=1)
print(total_mark_stu)

[279. 249. 219.]


In [ ]:
# The maximum mark of each student
max_mark_stu=np.max(marks,axis=1)
print(max_mark_stu)

[95. 85. 75.]


In [ ]:
# standard deviation of each subject
std_dev_sub=np.std(marks,axis=0)
print(std_dev_sub)
std_dev_stu=np.std(marks,axis=1)
print(std_dev_stu)

[8.16496581 8.16496581 8.16496581]
[1.63299316 1.63299316 1.63299316]


In [ ]:
# adding new students mark to the array
c=[65,67,69]
marks=np.vstack((marks,c))
print(marks)

[[95. 93. 91.]
 [85. 83. 81.]
 [75. 73. 71.]
 [65. 67. 69.]]


In [ ]:
# max-min normalizarion
norm=((marks-np.min(marks))/(np.max(marks)-np.min(marks)))
norm

array([[1.        , 0.93333333, 0.86666667],
       [0.66666667, 0.6       , 0.53333333],
       [0.33333333, 0.26666667, 0.2       ],
       [0.        , 0.06666667, 0.13333333]])

In [ ]:
# z score normalization
Z_norm=((marks-np.mean(marks))/np.std(marks))
Z_norm

array([[ 1.59469319,  1.39535654,  1.19601989],
       [ 0.59800994,  0.3986733 ,  0.19933665],
       [-0.3986733 , -0.59800994, -0.79734659],
       [-1.39535654, -1.19601989, -0.99668324]])

In [ ]:
print(total_mark_stu)
rank=np.argsort(total_mark_stu)
rank


[279. 249. 219.]


array([2, 1, 0])