<a href="https://colab.research.google.com/github/ShobigaBoopeshKumar/Python_Libraries/blob/main/PANDAS/Python_Projects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Student Mark Analyzer**

In [20]:
import numpy as np
stu=int(input("Enter the no of Students\t:"))
sub=int(input("Enter the no of Subjects\t:"))
marks=np.zeros((stu,sub))
for i in range(stu):
  for j in range(sub):
    marks[i][j]=int(input(f"Enter the marks of student {i+1} in subject {j+1} :"))
print(marks)


Enter the no of Students	:4
Enter the no of Subjects	:3
Enter the marks of student 1 in subject 1 :95
Enter the marks of student 1 in subject 2 :85
Enter the marks of student 1 in subject 3 :75
Enter the marks of student 2 in subject 1 :92
Enter the marks of student 2 in subject 2 :82
Enter the marks of student 2 in subject 3 :72
Enter the marks of student 3 in subject 1 :91
Enter the marks of student 3 in subject 2 :81
Enter the marks of student 3 in subject 3 :61
Enter the marks of student 4 in subject 1 :89
Enter the marks of student 4 in subject 2 :79
Enter the marks of student 4 in subject 3 :69
[[95. 85. 75.]
 [92. 82. 72.]
 [91. 81. 61.]
 [89. 79. 69.]]


In [28]:
# The avg marks of the each student

avg_mark_stu=np.mean(marks,axis=1)
print(np.round(avg_mark_stu,2))

# The avg mark of each subject
avg_marks_sub=np.mean(marks,axis=0)
print(np.round(avg_marks_sub,2))


[85.   82.   77.67 79.  ]
[91.75 81.75 69.25]


In [29]:
# The total mark of each student
total_mark_stu=np.sum(marks,axis=1)
print(total_mark_stu)

[255. 246. 233. 237.]


In [30]:
# The maximum mark of each student
max_mark_stu=np.max(marks,axis=1)
print(max_mark_stu)
# The highest mark in each subject
max_mark_sub=np.max(marks,axis=0)
print(max_mark_sub)

[95. 92. 91. 89.]
[95. 85. 75.]


In [31]:
# standard deviation of each subject
std_dev_sub=np.std(marks,axis=0)
print(std_dev_sub)
std_dev_stu=np.std(marks,axis=1)
print(std_dev_stu)

[2.16506351 2.16506351 5.2141634 ]
[ 8.16496581  8.16496581 12.47219129  8.16496581]


In [32]:
# adding new students mark to the array
c=[65,67,69]
marks=np.vstack((marks,c))
print(marks)

[[95. 85. 75.]
 [92. 82. 72.]
 [91. 81. 61.]
 [89. 79. 69.]
 [65. 67. 69.]]


In [38]:
# max-min normalizarion
norm=((marks-np.min(marks))/(np.max(marks)-np.min(marks)))
np.round(norm,2)

array([[1.  , 0.71, 0.41],
       [0.91, 0.62, 0.32],
       [0.88, 0.59, 0.  ],
       [0.82, 0.53, 0.24],
       [0.12, 0.18, 0.24]])

In [37]:
# z score normalization
Z_norm=((marks-np.mean(marks))/np.std(marks))
np.round(Z_norm,2)

array([[ 1.62,  0.66, -0.3 ],
       [ 1.33,  0.37, -0.59],
       [ 1.23,  0.27, -1.64],
       [ 1.04,  0.08, -0.87],
       [-1.26, -1.07, -0.87]])

In [36]:
print(total_mark_stu)
rank=np.argsort(total_mark_stu[::-1])
rank


[255. 246. 233. 237.]


array([1, 0, 2, 3])